export const KeyPaths = {
    accessKey: "6d5846fd-a4b9-49be-bc1b-0290447b1dcf",
}

export const PagePaths = {
    home: "/",
    about: "/about",
    work: "/work",
    contact: "/contact"
}

export const ImagePaths = {
    hero: "/Hero.png",
    adobePhotoshop: "/Skills/Adobe Photoshop.png",
    aseprite: "/Skills/Aseprite.png",
    bootstrap: "/Skills/Bootstrap.png",
    cSharp: "/Skills/Csharp.png",
    css: "/Skills/CSS.png",
    expressJS: "/Skills/ExpressJS.png",
    git: "/Skills/Git.png",
    hardware: "/Skills/Hardware.png",
    html: "/Skills/HTML.png",
    inky: "/Skills/Inky.png",
    java: "/Skills/Java.png",
    javaScript: "/Skills/JavaScript.png",
    mongoDB: "/Skills/MongoDB.png",
    mySQL: "/Skills/MySQL.png",
    network: "/Skills/Network.png",
    nodeJS: "/Skills/NodeJS.png",
    npm: "/Skills/NPM.png",
    postgreSQL: "/Skills/PostgreSQL.png",
    react: "/Skills/React.png",
    sass: "/Skills/Sass.png",
    server: "/Skills/Server.png",
    tailwindCSS: "/Skills/Tailwind CSS.png",
    unity: "/Skills/Unity.png",
    visualBasic: "/Skills/Visual Basic.png",

    universityOfLuzon: "/UL.png",
    firstRCPE: "/Certificates/1st Research Colloquium & Project Exhibits.png",
    androidAppDev: "/Certificates/Android App Development.png",
    backEndDevAPI: "/Certificates/Back End Development & APIs.png",
    bsitDiploma: "/Certificates/BSIT Diploma.png",
    frontEndDevLib: "/Certificates/Front End Development Libraries.png",
    jsAlgoDS: "/Certificates/JavaScript Algorithms & Data Structures.png",
    relationalDB: "/Certificates/Relational Database.png",
    resWebDes: "/Certificates/Responsive Web Design.png",
    tesdaCSS: "/Certificates/TESDA CSS.png",
    
    jourdansSnackCorner: "/Works/Jourdans Snack Corner.png",
    randomQuoteMachine: "/Works/Random Quote Machine.png",
    drumMachine: "/Works/Drum Machine.png",
    todoApp: "/Works/Todo App.png",
    musicPlayer: "/Works/Music Player.png",
    urlShortener: "/Works/URL Shortener Microservice.png",
    exerciseTracker: "/Works/Exercise Tracker.png",
    pulpRpg: "/Works/PULP RPG.png",
    pulpRpgDoc: "/Works/PULP RPG Documentation.png",
    graphicsDesign: "/Works/Graphics Design.jpg",
    pixelArt: "/Works/Pixel Art.png",
    vbStudentSystem: "",
    mernCrudApp: "",
}

export const ExternalPaths = {
    cv: "/Carlos Johncent Ventura CV.pdf",
    facebook: "https://www.facebook.com/johncent.ventura.7",
    github: "https://github.com/JohncentVentura",
    pinterest: "https://ph.pinterest.com/johncentventura/pins/",

    adobePhotoshop: "",
    aseprite: "",
    bootstrap: "",
    cSharp: "",
    css: "",
    expressJS: "",
    git: "",
    hardware: "",
    html: "",
    inky: "",
    java: "",
    javaScript: "",
    mongoDB: "",
    mySQL: "",
    network: "",
    nodeJS: "",
    npm: "",
    postgreSQL: "",
    react: "",
    sass: "",
    server: "",
    tailwindCSS: "",
    unity: "",
    visualBasic: "",

    freeCodeCamp: "https://www.freecodecamp.org/learn/",
    universityOfLuzon: "https://ul.edu.ph/",
    firstRCPE: "",
    androidAppDev: "",
    backEndDevAPI: "https://www.freecodecamp.org/certification/Johncent-Developer/back-end-development-and-apis",
    bsitDiploma: "",
    frontEndDevLib: "https://www.freecodecamp.org/certification/Johncent-Developer/front-end-development-libraries",
    jsAlgoDS: "https://www.freecodecamp.org/certification/Johncent-Developer/javascript-algorithms-and-data-structures",
    relationalDB: "https://www.freecodecamp.org/certification/Johncent-Developer/relational-database-v8",
    resWebDes: "https://www.freecodecamp.org/certification/Johncent-Developer/responsive-web-design",
    tesdaCSS: "",

    jourdansSnackCorner: "https://jourdans-snack-corner.netlify.app",
    gitJourdansSnackCorner: "https://github.com/JohncentVentura/Jourdans-Snack-Corner",
    randomQuoteMachine: "https://cjv-random-quote-machine.netlify.app",
    gitRandomQuoteMachine: "https://github.com/JohncentVentura/Random-Quote-Machine",
    drumMachine: "https://cjv-drum-machine.netlify.app",
    gitDrumMachine: "https://github.com/JohncentVentura/Drum-Machine",
    todoApp: "https://cjv-todo-app.netlify.app",
    gitTodoApp: "https://github.com/JohncentVentura/Todo-App",
    musicPlayer: "https://cjv-music-player.netlify.app",
    gitMusicPlayer: "https://github.com/JohncentVentura/Music-Player",
    urlShortener: "https://url-shortener-microservice-frse.onrender.com",
    gitUrlShortener: "https://github.com/JohncentVentura/URL-Shortener-Microservice",
    exerciseTracker: "https://exercise-tracker-9k5u.onrender.com",
    gitExerciseTracker: "https://github.com/JohncentVentura/Exercise-Tracker",
    pulpRpg: "https://drive.google.com/file/d/1UoWxtuWfohXF-6YLGBBe0MQ9s2_f3GDN/view?usp=sharing",
    gitPulpRpg: "https://github.com/JohncentVentura/PULP-RPG-Scripts",
    pulpRpgDoc: "https://pulp-rpg-doc.netlify.app",
    gitPulpRpgDoc: "https://github.com/JohncentVentura/PULP-RPG-Documentation",
    graphicsDesign: "https://ph.pinterest.com/johncentventura/graphics-design/  ",
    pixelArt: "https://ph.pinterest.com/johncentventura/pixel-art/",
    vbStudentSystem: "",
    gitVbStudentSystem: "https://github.com/JohncentVentura/Student-Registration-System",
    mernCrudApp: "",
    gitMernCrudApp: "https://github.com/JohncentVentura/MERN-CRUD-APP",

    phone: "tel:0956-419-6962",
    email: "mailto:johncent.ventura@gmail.com",
    address: "https://www.google.com/maps/place/Pozorrubio,+Pangasinan/@16.1134395,120.48211,13z/data=!3m1!4b1!4m6!3m5!1s0x33916cb5f40f6be3:0xeabbbddf910cf96c!8m2!3d16.1163874!4d120.5431187!16zL20vMDZqemxx?entry=ttu",
}